### ISSUE TITLE
Autogenerated Measure name "with space" issue [concerns Wiki: Measure Packaging] [Evaluation scenario 4]

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#11]
It seems like space character is not accepted in Measure naming convention. 
However, default measure name ( "Direct Measure" ) has a space which leads to an error, if not changed to another name w/o space.

**Comment by alebagnato** [comment]
Many thanks for this report @Prasoonda

**Comment by aabherve** [comment]
fixed
