### ISSUE TITLE
Installing elastic search on an older linux version

### ISSUE THREAD

**Issue by MathiasBollaert** [ITEA3-Measure/MeasurePlatform#15]
By default, elastic search requires a 3.5+ Kernel with CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER options compiled, or the engine won't start.

To avoid this, edit the config/elasticsearch.yml file, adding the following line (strictly identical):
bootstrap.seccomp: false

**Comment by alebagnato** [comment]
Many thanks again @MathiasBollaert

**Comment by aabherve** [comment]
NA
