### ISSUE TITLE
Minimal memory required to run elasticsearch

### ISSUE THREAD

**Issue by MathiasBollaert** [ITEA3-Measure/MeasurePlatform#16]
When running the Measure platrform on a constrainted environment (such as a virtual machine), I was faced to the following issue:

- First starting elastic search, which went fine
- Then launching kibana, after a few seconds, elastic search was killed

After reading system log in var/log/messages I found that elastic search was killed because of running out of memory.

I changed the settings of the virtual machine to 3Go memory (previously 1Go), and it solved the problem.

So I recommend running the Measure Platform with at least 3Go of memory.

**Comment by alebagnato** [comment]
Many thanks @MathiasBollaert for your feedback and comments. That is very helpful and will be expressely included in the documentation of the next version of our MEASURE Platform

**Comment by aabherve** [comment]
NA
