### ISSUE TITLE
Measure wiki (For adding new metrics jar)

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#17]
The part where we would want to add Measure from the MEASURE repository (For example : The one from Sonar cubes) is not very clear. I suppose we would need to generate jars to add them in the project. 

Looking at the wiki [1] , Manual measure implementation gives some ideas but was not enough. And also the part showing Maven project template has a broken link.

[1] https://github.com/ITEA3-Measure/MeasurePlatform/wiki/Manual-Measure-Implementation

**Comment by alebagnato** [comment]
Hi @Prasoonda Many thanks for your feedback and enhancement request. We will update the wiki following your suggestions.

**Comment by aabherve** [comment]
Packaging of measures as ZIP file is documented in this page : https://github.com/ITEA3-Measure/MeasurePlatform/wiki/Manual-Measure-Implementation

We could plane to provide a release containing pacakged measures in order to facilitate the usage of this measures
