### ISSUE TITLE
River measure needs property JWT token

### ISSUE THREAD

**Issue by alexandrasandulescu** [ITEA3-Measure/MeasurePlatform#18]
When adding a token as property using the measure instance form, the value cannot be read using getProperty in DirectMeasure. The token length is 303.

**Comment by aabherve** [comment]
In current version of the platform a preperty value is a varchar(255). I have increase the size of this field in the in-developement version of the platform.

If it's a blocking issue in you current work for the first evaluation, we can create a temporary branch in github with this fix.

**Comment by alexandrasandulescu** [comment]
It is not blocking. I hardcoded the value in the custom measure code. I will modify it after the next release.

**Comment by aabherve** [comment]
Property Value max size increased to 1024
