### ISSUE TITLE
automatically add "measureplatform" in mysql at install time

### ISSUE THREAD

**Issue by adilupei** [ITEA3-Measure/MeasurePlatform#19]
automatically add "measureplatform" in mysql at install time or check if the database already exists

**Comment by adilupei** [comment]
another option is to add in this step in documentation (I did not find it)

**Comment by aabherve** [comment]
Documented in this page https://github.com/ITEA3-Measure/MeasurePlatform/wiki/Platform-Installation  > MySQL Installation

We could plan to use DOCKER to automatise the platform installation
