### ISSUE TITLE
Random generator download link [1st evaluation]

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#2]
The link for downloading suggested measure "Random generator" https://github.com/ITEA3-Measure/Measures/blob/master/Examples/RandomGenerator/RandomGenerator.zip  does not work anymore. Please have a look.
Thanks.

**Comment by alebagnato** [comment]
Thank you @Prasoonda for this issue. We will look into it and fix it asap

**Comment by aabherve** [comment]
Add measures in Measure/_Example git hub directory
Fix the link in the wiki
