### ISSUE TITLE
Measure Logs - can't load image

### ISSUE THREAD

**Issue by adilupei** [ITEA3-Measure/MeasurePlatform#20]
when accessing Platform/Measure Collect menu there is an image that can't be loaded. On mouse over shows "localhost connection refused to connect

Extra infos:
- logged as Administrator
- measure platform is installed in a vmware machine and accessed externally using it's public profile
- browser: Google Chrome
<img width="1440" alt="screen shot 2017-09-28 at 10 31 16" src="https://user-images.githubusercontent.com/534538/30954325-692feea8-a438-11e7-9457-1bbf386c84ac.png">

**Comment by aabherve** [comment]
it's not an image,  it's a kibana graph integrated as iframe. Pleasue check that kibana is installed and runing.
On my side , i will study potential issues with Chrome and vmware

**Comment by adilupei** [comment]
I have kibana running on 5601 port (default). I can access it using external vm IP (http://192.168.174.162:5601/app/kibana#/management/kibana/index?_g=()). I have no index pattern configured in kibana.

**Comment by aabherve** [comment]
Could you check the **measure.kibana.adress** paremeter in application.properties and try to replace it by  192.168.174.162:5601

In this version, you will have to create an index pattern name "measure" in kibana. ( In developement version of the platform, index and managed automaticly by the platform).

**Comment by adilupei** [comment]
measure.kibana.address=localhost:5601. I will enter vm's public ip.

**Comment by adilupei** [comment]
now it works but I have to do configure an index pattern in kibana. maybe it is related to the measure or measure_instance I've added. I can't find anything in documentation regarding kibana configuration. (I didn't run any measure at this point)

**Comment by aabherve** [comment]
In this version of the platform, you have to : 
- Execute one measure and store at least one data.
- Create the "measure" index pattern in kibana. ( the kibana index pattern index can't be created if  no data has bean  pushed under the corresponding elasticsearch index)

**Comment by adilupei** [comment]
I've added it manually but I can't see any visualization. see attached screenshot.
<img width="1364" alt="screen shot 2017-09-28 at 13 35 01" src="https://user-images.githubusercontent.com/534538/30965274-8083fcbe-a45d-11e7-90bd-6ad27c6abf55.png">

**Comment by aabherve** [comment]
Index are now managed automaticly by the platform
