### ISSUE TITLE
can't unarchive mmt

### ISSUE THREAD

**Issue by adilupei** [ITEA3-Measure/MeasurePlatform#21]
I've downloaded zip file twice (www.montimage.com/resources/downloads/measure/20170901_MMT_MEASURE.zip ) and I have the same output.

_unzip 20170901_MMT_MEASURE.zip 
Archive:  20170901_MMT_MEASURE.zip
   creating: 20170901_MMT_MEASURE/
  inflating: 20170901_MMT_MEASURE/20170823-mmt-deb.tar.gz  
   creating: 20170901_MMT_MEASURE/doc/
  inflating: 20170901_MMT_MEASURE/doc/MMT_Manual.pdf  
  inflating: 20170901_MMT_MEASURE/doc/VM_Architecture.pdf  
  inflating: 20170901_MMT_MEASURE/mmt-20170821.ova   bad CRC 7537b3bf  (should be 779ce7d3)
  inflating: 20170901_MMT_MEASURE/README_  

I've tried to import the ova and I've got some errors. For sure there is some problem in zip file.

In order to evaluate MMT I will need access to your amazon vm. My public IP is 91.199.104.6.

**Comment by Mallouli** [comment]
I'll send you another link to download directly the .ova file

**Comment by Mallouli** [comment]
Please try www.montimage.com/resources/downloads/measure/mmt-20170821.ova
This will allow you to work with the virtual machines of MMT
Do not hesitate to see the description of the architecture in the file : 
 www.montimage.com/resources/downloads/measure/VM_Architecture.pdf

If you would like to use the debian packages to install MMT, please send me an email

**Comment by adilupei** [comment]
I will try it next week. thank you!
