### ISSUE TITLE
Programatic measure retrieval.

### ISSUE THREAD

**Issue by teodor-stoenescu** [ITEA3-Measure/MeasurePlatform#23]
This is an improvement proposal as per Scenario 5 of [the first evaluation](https://github.com/ITEA3-Measure/MeasurePlatform/wiki/1st-evaluation-2017).

Currently the platform supports on demand and periodic measures retrieval. However a periodic measure retrieval doesn't make much sense for evaluating a repository, for example. On the other hand, manually running a measure is an extra step that can surely be automated.

It would be great if the platform would expose some sort of API for automatically running measures that can be integrated with existing software development tools (such as git hooks, or github webhooks)

**Comment by aabherve** [comment]
The REST api already exist  (the api is used by the web application ) but if we went to expose it to external client, we will have to deploy an authentification  system  for services provided by the api ( probably based on a token system)

**Comment by aabherve** [comment]
The API is now opened
