### ISSUE TITLE
Open protocol

### ISSUE THREAD

**Issue by teodor-stoenescu** [ITEA3-Measure/MeasurePlatform#25]
This is an improvement proposal as per Scenario 5 of [the first evaluation](https://github.com/ITEA3-Measure/MeasurePlatform/wiki/1st-evaluation-2017).

It is sometimes hard to collect measures from the platform alone. The platform agend addresses this need but introduces a major drawback, namely the necessity of having at least a JRE on the client system. Personallly I see two problems with this. On the one hand, this makes it difficult to collect measures from embedded systems where disk and memory are limited, while on the other hand it greatly increases the attack surface of the client system.

It would be great if the platform would expose an open protocol (preferably HTTP in order to pass most firewall configurations), allowing us to implement agents in other programming languages (such as C for embedded systems, or anything else available on the client system), superseeding the current platform agent.

**Comment by aabherve** [comment]
Communication between agents and the platform is based on REST service. The developement of an agent based on another technology is possible.
