### ISSUE TITLE
[enhancement] Use project/phase name instead of database id

### ISSUE THREAD

**Issue by adilupei** [ITEA3-Measure/MeasurePlatform#26]
Please use project/phase names instead of id(s) to increase usability of measurement ui. It's fine to use id(s) for a few projects and phases but it will be complicated if more data is added into the platform.

**Comment by aabherve** [comment]
Used project name as id required the uniqueness of the project name. As the platform supprot multiple users whith separate workspace, this uniqueness  can't be can not be guaranteed
