### ISSUE TITLE
[bug] internal error on create measure view

### ISSUE THREAD

**Issue by adilupei** [ITEA3-Measure/MeasurePlatform#27]
i've got the following error trying to add a measure view:
<img width="1440" alt="screen shot 2017-10-02 at 10 27 31" src="https://user-images.githubusercontent.com/534538/31067609-6de97b2c-a75c-11e7-9023-56846599a30a.png">

**Comment by alebagnato** [comment]
Hi @adilupei, could you give us more details on the executed testing scenario that made this bug appear?We are not able to reproduce it unfortunatelly.
Many thanks in advance for your help,
Alessandra

**Comment by adilupei** [comment]
there was nothing special. I was just trying to add a new measure view. That message showed up for a few seconds (3-5 seconds) and it is not very descriptive.

do you have any log files where I can look for more details?

**Comment by aabherve** [comment]
Why do you try to add a view by declaring it in the DB ?
