### ISSUE TITLE
MeasureInstance HTML form rendering

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#3]
In measure instance, there is this unusual rendering in html table form(image attached) . Please have a look.

![measureinstance](https://user-images.githubusercontent.com/29273696/30025829-90ee9172-917a-11e7-8cc7-16e054aa570e.PNG)

**Comment by Mallouli** [comment]
This may happen because of the size of the text field. This size can fixed and not relative to the popup size

**Comment by alebagnato** [comment]
Hi @Prasoonda thanks again! Can you give us information on the operating system you are running MEASURE? Thanks in advance

**Comment by Prasoonda** [comment]
Thanks @Mallouli @alebagnato for getting to it. 
I am using Windows 10. 
I am not sure about the fixed text field. In anycase, it seems unusual. I tried zooming and unzooming, nothing particular changed.

**Comment by aabherve** [comment]
Fixed in the https://github.com/ITEA3-Measure/MeasurePlatform/commit/1257a1f1f5326390950b59911f0ca200b958671c commit
