### ISSUE TITLE
could not get result with Amazon VM [Evaluation Scenario 3]

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#30]
I get an error, after following exact process from the tutorial. It seems like there is some mismatch with SMMapi version used and the measure platform.
![image](https://user-images.githubusercontent.com/29273696/31284839-118cbd4c-aaba-11e7-932e-b763988fd0c8.png)

**Comment by Prasoonda** [comment]
https://github.com/ITEA3-Measure/MeasurePlatform/wiki/Manual-Measure-Implementation

Maybe the version is 2.08 to be used.

> <repositories>
>   <repository>
>     <id>Modelio</id>
>     <url>http://repository.modelio.org/</url>
>   </repository>
> </repositories>
> <dependencies>
>   <dependency>
>     <groupId>org.measure.smmmeasure.api</groupId>
>     <artifactId>SMMMeasureApi</artifactId>
>     <version>0.2.08</version>
>   </dependency>	
> </dependencies>

**Comment by Mallouli** [comment]
As stated in the description of the scenario, the amazon machine where MMT is running is not open to all the IP addresses. If you deployed the MEASURE platform locally, you need to provide us your IP address so that we can add it to the authorized IPs.
If not, please check again.

**Comment by Prasoonda** [comment]
Thanks for Email.

Surprisingly I was able to access it with browser, so I continued…

But, if it helps please find my IP address here : 10.78.4.121

Thanks,
Prasoon
De : Mallouli [mailto:notifications@github.com]
Envoyé : Wednesday, October 11, 2017 12:26 PM
À : ITEA3-Measure/MeasurePlatform <MeasurePlatform@noreply.github.com>
Cc : DADHICH Prasoon <prasoon.dadhich@softeam.fr>; Assign <assign@noreply.github.com>
Objet : Re: [ITEA3-Measure/MeasurePlatform] could not get result with Amazon VM [Evaluation Scenario 3] (#30)


As stated in the description of the scenario, the amazon machine where MMT is running is not open to all the IP addresses. If you deployed the MEASURE platform locally, you need to provide us your IP address so that we can add it to the authorized IPs.
If not, please check again.

**Comment by Mallouli** [comment]
Excellent news.
I just added your IP to the authorized lists of IPs.

--
Dr. Wissam Mallouli
---------------------------------------
R&D Project Manager
Montimage
39 rue Bobillot
75013 Paris
---------------------------------------------------------
Mobile : +33 6 95 93 33 39
Email : wissam.mallouli@montimage.com


2017-10-11 13:14 GMT+02:00 Prasoonda <notifications@github.com>:

**Comment by alebagnato** [comment]
Hi @Mallouli @Prasoonda, I am closing the issue right now, good that everything is solved :)
