### ISSUE TITLE
Class complexity measure [Scenario 3 evaluation]

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#32]
Class complexity measure does not work. While going through code, I saw the Measure name with space: which is not accepted in the measure platform. So basically, we would have to remove the space there. 
After that, there were some other errors in the logs 
![image](https://user-images.githubusercontent.com/29273696/31494414-7b57c2ce-af53-11e7-8906-da523cadf924.png)

**Comment by aabherve** [comment]
Out of Scope : related to measure implementation
