### ISSUE TITLE
CpuUsage Measure [Scenario 3 evaluation]

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#33]
I received nullpointer exception on measure platform when executing. Apparently there seems to be a bug in this measure with the measure platform.

![image](https://user-images.githubusercontent.com/29273696/31495059-52d6f844-af56-11e7-85df-89395813d764.png)

**Comment by aabherve** [comment]
Out of Scope : related to measure implementation
