### ISSUE TITLE
Visualizing measure steps in wiki

### ISSUE THREAD

**Issue by Prasoonda** [ITEA3-Measure/MeasurePlatform#4]
Steps to visualize measure, (such as selecting index in kibana) could be enhanced and linked to 1st evaluation wiki.
**https://github.com/ITEA3-Measure/MeasurePlatform/wiki/Visualise-Complex-Measure**

![image](https://user-images.githubusercontent.com/29273696/30030082-fc41ac1e-918b-11e7-996e-1fa0ee84c3e6.png)

**Comment by aabherve** [comment]
THe process has bean automated in current platform verion
