### ISSUE TITLE
[enhancement][measure instances list] Add tooltips on test/execute/edit/delete buttons

### ISSUE THREAD

**Issue by NG-GOM** [ITEA3-Measure/MeasurePlatform#47]
Using the buttons of the "Measures instances" page (`<host_measurePlatform>/#/project/<project_ID>/configuration/instances`) is not very intuitive for new users.

Buttons of the "Measures instances" shall have tooltips assigned to explicit their name and usage.

**Comment by aabherve** [comment]
Resolved in 0.8
