### ISSUE TITLE
Visible scope fields

### ISSUE THREAD

**Issue by teodor-stoenescu** [ITEA3-Measure/MeasurePlatform#7]
When viewing measure instances all scope fields are visible. This is clearly a bad security practice since some of those fields contain sensitive information such as passwords or key files. Please provide a mechanism for selecting which scope fields are visible!
![scr3](https://user-images.githubusercontent.com/12010162/30153511-91543102-93bf-11e7-9282-a18434229418.png)

**Comment by aabherve** [comment]
Fixed in last version of the platform. Scope properties can now be typed  and the is a type "PASSWORD"
