### ISSUE TITLE
Platform is looking for  MeasureMetadata.xml in the wrong directory

### ISSUE THREAD

**Issue by alexandrasandulescu** [ITEA3-Measure/MeasurePlatform#8]
When I tried to upload a Measure example from [1], the archive would contain the file "MeasureMetadata.xml" inside the "metadata" directory. The code lead me to "src/main/java/org/measure/platform/core/impl/MeasureCatalogueService.java". 

The suggestion is to change the place where platform searches for "MeasureMetadata.xml". Otherwise, all examples from [1] should be modified.

[1] https://github.com/ITEA3-Measure/Measures

**Comment by aabherve** [comment]
To be deployed , the measures has to be packaged foloing this process : 
https://github.com/ITEA3-Measure/MeasurePlatform/wiki/Manual-Measure-Implementation
https://github.com/ITEA3-Measure/MeasurePlatform/wiki/Measure-Packaging

Did you  folow this process to package the measure ?

**Comment by alexandrasandulescu** [comment]
I created a pr for automatically packaging the .zip SMM measure file.
I do not have PR rights on [1]. How can I send the patch?

Thank you

[1] https://github.com/ITEA3-Measure/Measures.git

**Comment by alexandrasandulescu** [comment]
PR [1] should fix this. The implementation is done for one single measure, but it can be extended for all measures in the [2] repo.

[1] https://github.com/ITEA3-Measure/Measures/pull/1
[2] https://github.com/ITEA3-Measure/Measures
