### ISSUE TITLE
SMMMeasureApi 0.5.00 not found

### ISSUE THREAD

**Issue by alexandrasandulescu** [ITEA3-Measure/MeasurePlatform#9]
Latest MeasurePlatform dependency:
\<dependency\>
      \<groupId>org.measure.smmmeasure.api\</groupId\>
      \<artifactId\>SMMMeasureApi\</artifactId\>
      \<version\>0.5.00\</version\>
\</dependency\>

Because of build failure, I tried to locate package version 0.5.00 but it is not present on [1].

[1] http://repository.modelio.org/org/measure/smmmeasure/api/SMMMeasureApi/

**Comment by alebagnato** [comment]
Hi @alexandrasandulescu Many thanks for submitting this issue. We will look into it asap. I wanted to ask you, on which operating system are you running your installation?
Thank you very much in advance

**Comment by alexandrasandulescu** [comment]
Hi @alebagnato,
My system is: 
Linux phat-jim 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

The url that cannot be accessed is:
http://repository.modelio.org/org/measure/smmmeasure/api/SMMMeasureApi/0.5.00/SMMMeasureApi-0.5.00.jar

**Comment by alebagnato** [comment]
Many thanks @alexandrasandulescu we will get back to you tomorrow!@aabherve @alinstef

**Comment by aabherve** [comment]
The developement project of the library is available at this url :
https://github.com/ITEA3-Measure/SMMMeasureApi

The SMMMeasureApi 0.5.00 has not be yet released , it's thwhy the jar is not available in the public repository.

In context of  the evaluation of ITEA3 Measure project, you have to work with the last released versions as presented in the wiki : 
Measure Platform  v0.5.0.2
SMMMeasureAPI 0.2.08

**Comment by alexandrasandulescu** [comment]
@aabherve, in pom.xml for tags/v.0.5.0.2 the required version of SMMMeasureApi is 0.4.00 [1].

[1] https://github.com/ITEA3-Measure/MeasurePlatform/blob/585fd056c187804a4c3f3d11c12bb82f9bb07273/pom.xml#L387
